name: dart_telegram_bot
description: A Telegram Bot API wrapper made to make fast Telegram bots with as less code as possible.
version: 0.5.2
homepage: https://github.com/KaikyuDev/dart-telegram-bot

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  logging: ^1.0.1

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.16.0
